### ISSUE TITLE
Export to PDF does not work

### ISSUE THREAD

**Issue by H-Max** [zbeanz/openerp-7-web-addons#4]
Hi there.

First of all great module : saves a lot of time...

I have an issue while trying to export in PDF :

2014-06-06 08:36:10,748 32630 ERROR
openerp.addons.web.http.HttpRequest.dispatch: An error occurred while handling a json request
Traceback (most recent call last):
  File "/home/openerp/web/addons/web/http.py", line 285, in dispatch
    r = method(self, **self.params)
  File "/home/openerp/web_addons/web_printscreen_zb/controllers.py", line 182, in index
    cookies={'fileToken': int(token)})
  File "/home/openerp/web/addons/web/http.py", line 332, in make_response
    response.set_cookie(k, v)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 992, in set_cookie
    self.charset))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/http.py", line 905, in dump_cookie
    value = to_bytes(value, charset)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_compat.py", line 106, in to_bytes
    raise TypeError('Expected bytes')
TypeError: Expected bytes

I have no idea where this is coming from...

**Comment by hectorh30** [comment]
Thanks to [Hans](http://www.zbeanztech.com/blog/advanced-printscreen-openerp-7?page=2) I managed to solve this very issue downgrading the Werkzeug version to 0.8.3: `pip install werkzeug==0.8.3`

**Comment by TemisC** [comment]
thanks! I can solve for Openerp7 Ubuntu 14.04 with ---> sudo pip install --upgrade werkzeug==0.8.3
